os: windows
language: c

script:
  - git clone https://github.com/wy3/yi.lua.git
  - cd yi.lua
  - choco feature enable -n=allowGlobalConfirmation
  - choco install make
  - choco install curl
  - choco install 7zip
  - curl https://www.lua.org/ftp/lua-5.3.4.tar.gz --output lua.tar.gz
  - 7z -y x lua.tar.gz
  - 7z -y x lua.tar
  - mv lua-5.3.4 lua53 && cd lua53 && make mingw && cd ..
  - curl http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.27-win64-bin.zip --output tcc-win64.zip
  - 7z e tcc-win64.zip -y
  - mkdir release
  - tcc/tcc.exe -impdef lua53/src/lua53.dll -o release/lua53.def
  - tcc/tcc.exe -shared -o release/yi.dll -w -I./lua53/src ./src/*.c ./release/lua53.def
