os: windows
language: c

script:
  - git clone https://github.com/wy3/yi.lua.git
  - cd yi.lua
  - mkdir release && mkdir release/build
  - cd vendor/lua534/src
  - cl /MT /O2 /c /DLUA_BUILD_AS_DLL *.c
  - ren lua.obj lua.o
  - ren luac.obj luac.o
  - link /DLL /IMPLIB:../../../release/lua53.lib /OUT:../../../release/lua53.dll *.obj 
  - link /OUT:../../../release/lua.exe lua.o ../../../release/lua5.3.0.lib
  - rm *.obj && cd ../../../release
  - cl /MP /GS- /GL /analyze- /W2 /I"../vendor/lua534/src" /c /D "WIN32" /D "UNICODE" /MT /Gd /Oy /Oi /Fa "./build/"
  - link /OUT:yi.dll ./lua53.lib
