os: windows
language: c

script:
  - git clone https://github.com/wy3/yi.lua.git
  - cd yi.lua
  - choco feature enable -n=allowGlobalConfirmation
  - choco install make curl 7zip tinycc
  - curl https://www.lua.org/ftp/lua-5.3.4.tar.gz --output lua.tar.gz
  - 7z -y x lua.tar.gz && 7z -y x lua.tar
  - mv lua-5.3.4 lua53 && cd lua53 && make mingw && cd ..
  - mkdir release
  - tcc -impdef lua53/src/lua53.dll -o release/lua53.def
  - tcc -shared -o release/yi.dll -w -I./lua53/src ./src/*.c ./release/lua53.def
