os: windows
language: c

script:
  - git clone https://github.com/wy3/yi.lua.git
  - cd yi.lua
  - choco feature enable -n=allowGlobalConfirmation
  - choco install make curl 7zip
  - curl https://www.lua.org/ftp/lua-5.3.4.tar.gz --output lua.tar.gz
  - 7z -y x lua.tar.gz && 7z -y x lua.tar
  - mv lua-5.3.4 lua53 && cd lua53 && make mingw && cd ..
  - mkdir release
  - gcc -shared -w -o release/yi.dll -I./lua53/src -DWIN32 -I__i686__ ./src/*.c -L./lua53/src -llua53
