os: windows
language: c

script:
  - git clone https://github.com/small-lua/milo.git
  - cd milo
  - choco feature enable -n=allowGlobalConfirmation
  - choco install make
  - choco install curl
  - choco install 7zip
  - curl https://www.lua.org/ftp/lua-5.3.5.tar.gz --output lua.tar.gz
  - 7z -y x lua.tar.gz
  - 7z -y x lua.tar
  - mv lua-5.3.5 lua53 && cd lua53 && make mingw && cd ..
  - gcc -shared -w -o milo.dll -I./lua53/src ./src/*.c -L./lua53/src -llua
